version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "5000:5000"
    command: ["python", "./src/main.py"]

  worker:
    restart: always
    build:
      context: ./webapp

