version: "3.9"

services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "5000:5000"
    command: ["python", "./src/main.py"]

    depends_on:
      - redis

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: ./webapp
    command: ['celery', '--workdir=./src', '-A', 'main.celery', 'worker']
    links:
      - redis
